name: Doxygen

# Trigger the action.
on:
  push:
    branches:
      - main
      - github-actions

# Job matrix
jobs:

  Doxygen:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - uses: mattnotmitt/doxygen-action@v1.9.4
        with:
          doxyfile-path: "Doc/Doxyfile.in"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          publish_dir: Doc/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "[Auto] Deploy Doxygen"
