name: MacOS

on: [push]

jobs:
  Clang:
    name: MacOS | Clang
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build_config: [Release, Debug]
        gcc_version: [11, 12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: "[Package] Install Clang"
        run: brew install llvm@${{ matrix.gcc_version }}

      - name: Generate Project
        run: cmake --preset="Clang" -std=gnu++17

      - name: Build Project
        run: cmake --build --preset="Clang ${{ matrix.build_config }}"

      - name: Run CTests
        run: ctest --preset="Clang ${{ matrix.build_config }}"


  GCC:
    name: MacOS | GCC
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build_config: [Release, Debug]
        gcc_version: [11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install suitable compiler
        run: brew install gcc@${{ matrix.gcc_version }}

      - name: Generate Project
        run: cmake --preset="GCC" -std=gnu++17

      - name: Build Project
        run: cmake --build --preset="GCC ${{ matrix.build_config }}"

      - name: Run CTests
        run: ctest --preset="GCC ${{ matrix.build_config }}"