# Copyright (c) 2022 Sapphire's Suite. All Rights Reserved.

name: Windows

# Trigger the action.
on:
  push:
    branches:
      - main
      - master
      - develop


# Settings common to all jobs.
defaults:
  run:
    shell: bash


# Variables common to all jobs.
env:
  CMAKE_OPTIONS: '-DSA_CI=1'


# Job matrix
jobs:

  MSVC_2019:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Generate Project
        run: cmake --preset=VS_2019 ${{ env.CMAKE_OPTIONS }}
      - name: Build Project
        run: cmake --build --preset="VS_2019 ${{ matrix.config }}" --verbose
      - name: Run CTests
        run: ctest --preset="VS_2019 ${{ matrix.config }}" -V